/* This file is automatically generated. Edits will be lost.*/
<<<<<<< HEAD
const int buildversion = 95;
=======
const int buildversion = 94;
>>>>>>> db05b8e7901d4f6e62b87007f6f78f58244d9b2c
const char buildconfig[] = "ASST2";
